server.port=18083
spring.application.name=instana-demo-retail

demo.central.url=http://192.168.252.35:18082
demo.max.age.seconds=120

logging.file.name=/var/log/instana-demo/retail-app.log
logging.level.root=INFO
server.error.include-message=always
